config/routes.rb
Rails.application.routes.draw do
  delete "produtos/:id", to: "produtos#destroy", as: :produto
  post "produtos", to: "produtos#create"
  get "produtos/new", to:"produtos#new"
  root to: "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.order(nome: :desc).limit 5
    @produtos_com_desconto = Produto.order(:preco).limit 1
  end
  
  def create
    produto = params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
    Produto.create produto
    redirect_to root_path
  end

  def destroy
    id = params[:id]
      Produto.destroy id
      redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= nav_bar brand: "Loja", brand_link: root_url do %>
    <%= menu_group do %>
      <%= menu_item "Criar novo produto", produtos_new_path %>
    <% end %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/produtos/index.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Preço</td>
      <td>Quantidade</td>
      <td colspan="1">
    </tr>
  </thead>
  <tbody>
  <% @produtos.each do |produto| %>
    <tr>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao%></td>
      <td><%= produto.preco %></td>
      <td><%= produto.quantidade %></td>
      <td><%= link_to "Remover", produto, method: :delete %></td>
    </tr>
  </tbody>
    <% end %>
</table>
<div class="alert alert-success" role="alert">
  <h3 class="alert-heading">Produto com desconto</h3>
</div>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Preço</td>
      <td>Quantidade</td>
    </tr>
  </thead>
  <tbody>
  <% @produtos_com_desconto.each do |produto| %>
    <tr>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao%></td>
      <td><%= produto.preco %></td>
      <td><%= produto.quantidade %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/produtos/new.html.erb
<%= form_for Produto.new do |form| %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :nome %>
        <%= form.text_field :nome, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :descricao %>
        <%= form.text_area :descricao, class:"form-control", rows:4 %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <div class="form-group">
        <%= form.label :preco %>
        <%= form.number_field :preco, step:0.01, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :quantidade %>
          <%= form.number_field :quantidade, class:"form-control" %>
        </div>
      </div>
  </div>
  <%= form.submit "Criar", class:"btn btn-primary" %>
<% end %>